pipeline {
    agent any

    tools {
        python 'Python3'  // Make sure you configured this under Global Tool Configuration
    }

    stage('Checkout') {
    steps {
        git branch: 'main',
            url: 'https://github.com/Hali1439/alx-backend-python.git',
            credentialsId: 'github-credentials'
    }
}


        stage('Install Dependencies') {
            steps {
                sh 'pip3 install -r messaging_app/requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'pytest --maxfail=1 --disable-warnings -q --junitxml=test-results.xml'
            }
            post {
                always {
                    junit 'test-results.xml'
                }
            }
        }
    }
}
